# Generated by Django 5.0.1 on 2024-02-18 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Title', models.CharField(max_length=12)),
                ('Plan_Duration', models.CharField(max_length=8)),
                ('Plan_Description', models.CharField(max_length=50)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Price', models.IntegerField()),
                ('Plan_Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Username', models.CharField(default='georgeksaji14@gmail.com', max_length=150)),
                ('App_Fname', models.CharField(max_length=10)),
                ('App_Lname', models.CharField(max_length=10)),
                ('App_Phone', models.CharField(max_length=20)),
                ('App_DOB', models.DateField()),
                ('App_Education', models.CharField(max_length=30)),
                ('App_Emp_Status', models.CharField(max_length=25)),
                ('App_LinkedIn', models.CharField(blank=True, max_length=200, null=True)),
                ('App_Image', models.CharField(max_length=200)),
                ('App_Hname', models.CharField(max_length=20)),
                ('App_Gender', models.CharField(max_length=10)),
                ('App_Street', models.CharField(max_length=200)),
                ('App_Dist', models.CharField(max_length=30)),
                ('App_Pin', models.IntegerField()),
                ('App_Date', models.DateField(default=django.utils.timezone.now)),
                ('App_Resume', models.CharField(max_length=100)),
                ('App_Status', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Username', models.CharField(default='lulu@gmail.com', max_length=150)),
                ('Emp_Firm', models.CharField(max_length=150)),
                ('Emp_Phone', models.CharField(max_length=10)),
                ('Emp_Street', models.CharField(max_length=150)),
                ('Emp_Dist', models.CharField(max_length=30)),
                ('Emp_State', models.CharField(default='Kerala', max_length=25)),
                ('Emp_Pin', models.IntegerField()),
                ('Emp_Image', models.CharField(max_length=200)),
                ('Emp_Date', models.DateField(default=django.utils.timezone.now)),
                ('Emp_Status', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM_Username', models.CharField(default='lulu@gmail.com', max_length=150)),
                ('Job_Title', models.CharField(max_length=150)),
                ('Job_Mode', models.CharField(max_length=15)),
                ('Job_Location', models.CharField(blank=True, max_length=150, null=True)),
                ('Job_Seats', models.IntegerField(default=0)),
                ('Job_Time_Type', models.CharField(max_length=15)),
                ('Job_Duration', models.IntegerField()),
                ('Job_Start', models.TimeField(blank=True, null=True)),
                ('Job_End', models.TimeField(blank=True, null=True)),
                ('Min_Job_Days', models.IntegerField()),
                ('Job_Day_Type', models.CharField(max_length=20)),
                ('Job_App_End', models.DateField()),
                ('Job_Description', models.CharField(max_length=1000)),
                ('Job_City', models.CharField(default='Kochi', max_length=20)),
                ('Job_State', models.CharField(default='Kerala', max_length=20)),
                ('Job_Status', models.BooleanField(default=True)),
                ('Employer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_App_Date', models.DateField(default=django.utils.timezone.now)),
                ('Job_App_Status', models.CharField(default='Applied', max_length=15)),
                ('Job_App_Interview_Date', models.DateField(blank=True, null=True)),
                ('Job_App_Interview_Time', models.TimeField(blank=True, null=True)),
                ('Job_App_Meeting_Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Job_App_Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Applicant_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.applicant')),
                ('Job_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Pay_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Holder_Name', models.CharField(max_length=20)),
                ('Card_No', models.DecimalField(decimal_places=0, max_digits=16, unique=True)),
                ('Exp_Date', models.DateField()),
                ('Card_Status', models.IntegerField(default=1)),
                ('Applicant_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.DateField(default=django.utils.timezone.now)),
                ('Applicant_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.applicant')),
                ('Card_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.pay_card')),
                ('Plan_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Review_Date', models.DateField(default=django.utils.timezone.now)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Reviewee_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.employer')),
                ('Reviewer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Username', models.CharField(default='jeffrey@gmail.com', max_length=150)),
                ('Staff_Fname', models.CharField(max_length=20)),
                ('Staff_Lname', models.CharField(max_length=20)),
                ('Staff_Phone', models.CharField(max_length=20)),
                ('Staff_DOB', models.DateField()),
                ('Staff_Hname', models.CharField(max_length=30)),
                ('Staff_Gender', models.CharField(max_length=10)),
                ('Staff_Street', models.CharField(max_length=20)),
                ('Staff_Dist', models.CharField(max_length=25)),
                ('Staff_Pin', models.IntegerField()),
                ('Staff_Date', models.DateField(default=django.utils.timezone.now)),
                ('Staff_Status', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Username', models.CharField(default='admin@gmail.com', max_length=150)),
                ('Event_Title', models.CharField(max_length=20)),
                ('Event_Organizer', models.CharField(max_length=20)),
                ('Event_Venue', models.CharField(max_length=150)),
                ('Event_Street', models.CharField(max_length=20)),
                ('Event_Dist', models.CharField(max_length=25)),
                ('Event_State', models.CharField(max_length=25)),
                ('Event_Email', models.CharField(max_length=25)),
                ('Event_Phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Event_Date', models.DateField()),
                ('Event_Time', models.TimeField()),
                ('Event_Description', models.CharField(max_length=150)),
                ('Event_Status', models.BooleanField(default=True)),
                ('Staff_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.staff')),
            ],
        ),
    ]
