# Generated by Django 5.0.1 on 2024-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Plan_Level',
            field=models.CharField(default='Basic', max_length=15),
        ),
    ]
