# Generated by Django 5.0.1 on 2024-02-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0002_plan_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Staff_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jp_app.staff'),
        ),
    ]
