# Generated by Django 5.0.1 on 2024-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0003_plan_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_Description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Plan_Title',
            field=models.CharField(max_length=20),
        ),
    ]
