# Generated by Django 5.0.1 on 2024-02-28 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0007_alter_payment_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Expiry_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
