# Generated by Django 5.0.1 on 2024-02-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jp_app', '0009_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Sender_status',
            field=models.BooleanField(default=True),
        ),
    ]
